### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by esilbe1** [rijksuniversiteit-groningen/BrightspaceWidgets#1]
Hi, we are a Brightspace institution and wanted to use your widget that shows if a course/courses are in an inactive state. However, when we install this, it only shows up at the course level. How can we get it to show up at the ORG level on an ORG homepage so students can see ALL active/inactive courses?

**Comment by allardnaber** [comment]
Sorry, I hadn't seen your question. This widget is only able to show the status of the org unit it is currently in. It is not aware of any other organizational units.
I think Brightspace does not support showing inactive courses to students at all.
